services:
    redis:
        image: redis:8.0-alpine
        container_name: redis
        command: redis-server --requirepass redis
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data
    postgres:
        container_name: postgres
        image: postgres:17.5-alpine
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    redis_data:
    pgdata:
